name: chunqizhuihao

on:
  workflow_dispatch:
  schedule:
    - cron: '1 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chunqizhuihao
        env:
          mhaqr99: ${{ secrets.mhaqr99 }}
        run: |
          echo $mhaqr99 | jq -r .lsnx2805 | /bin/bash
          echo $yfl02 | jq -r .y285 | /bin/bash
          echo $di119 | jq -r .bm626 | /bin/bash
          echo $sqfc72 | jq -r .k20 | /bin/bash
          echo $ajiy3 | jq -r .pvm1 | /bin/bash
          echo $bp3030 | jq -r .jbz9926 | /bin/bash
          echo $l852 | jq -r .gekz2 | /bin/bash
          echo $yshm9 | jq -r .is343 | /bin/bash
          echo $mdjz7 | jq -r .xdto977 | /bin/bash
          echo $tv8054 | jq -r .wnz49 | /bin/bash
          echo $wws114 | jq -r .mq70 | /bin/bash
          echo $yb24762 | jq -r .gpc76866 | /bin/bash

